<?php

/**
 * BaseReglaCostoPorMinuto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    paranoid-web
 * @subpackage model
 * @author     Paranoid Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReglaCostoPorMinuto extends Regla
{
    public function setUp()
    {
        parent::setUp();
        
    }
}