<?php

/**
 * BaseReglaDestino
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Prefijos
 * 
 * @method Doctrine_Collection getPrefijos() Returns the current record's "Prefijos" collection
 * @method ReglaDestino        setPrefijos() Sets the current record's "Prefijos" collection
 * 
 * @package    paranoid-web
 * @subpackage model
 * @author     Paranoid Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReglaDestino extends Regla
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Prefijo as Prefijos', array(
             'refClass' => 'ReglaPrefijo',
             'local' => 'regla_id',
             'foreign' => 'prefijo_id'));
    }
}