generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        fields: [username]
      form:
        class: sfGuardUserAdminForm
      edit:
        title: Editar Usuario Paranoid
      new:
        title: Nuevo Usuario Paranoid
