<?php

/**
 * BaseEstadisticas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuarios
 * @property integer $totales
 * @property integer $ok
 * @property integer $fallidas
 * @property integer $sospechosas
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getUsuarios()    Returns the current record's "usuarios" value
 * @method integer      getTotales()     Returns the current record's "totales" value
 * @method integer      getOk()          Returns the current record's "ok" value
 * @method integer      getFallidas()    Returns the current record's "fallidas" value
 * @method integer      getSospechosas() Returns the current record's "sospechosas" value
 * @method Estadisticas setId()          Sets the current record's "id" value
 * @method Estadisticas setUsuarios()    Sets the current record's "usuarios" value
 * @method Estadisticas setTotales()     Sets the current record's "totales" value
 * @method Estadisticas setOk()          Sets the current record's "ok" value
 * @method Estadisticas setFallidas()    Sets the current record's "fallidas" value
 * @method Estadisticas setSospechosas() Sets the current record's "sospechosas" value
 * 
 * @package    paranoid-web
 * @subpackage model
 * @author     Paranoid Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadisticas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estadisticas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuarios', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('totales', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ok', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fallidas', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sospechosas', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}