<?php

/**
 * BaseReglaPrefijo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $regla_id
 * @property integer $prefijo_id
 * 
 * @method integer      getReglaId()    Returns the current record's "regla_id" value
 * @method integer      getPrefijoId()  Returns the current record's "prefijo_id" value
 * @method ReglaPrefijo setReglaId()    Sets the current record's "regla_id" value
 * @method ReglaPrefijo setPrefijoId()  Sets the current record's "prefijo_id" value
 * 
 * @package    paranoid-web
 * @subpackage model
 * @author     Paranoid Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReglaPrefijo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regla_prefijo');
        $this->hasColumn('regla_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('prefijo_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}