<?php

/**
 * BaseReglaPerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $regla_id
 * @property integer $perfil_id
 * 
 * @method integer     getReglaId()   Returns the current record's "regla_id" value
 * @method integer     getPerfilId()  Returns the current record's "perfil_id" value
 * @method ReglaPerfil setReglaId()   Sets the current record's "regla_id" value
 * @method ReglaPerfil setPerfilId()  Sets the current record's "perfil_id" value
 * 
 * @package    paranoid-web
 * @subpackage model
 * @author     Paranoid Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReglaPerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regla_perfil');
        $this->hasColumn('regla_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}