generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        informarAlertas:
          label: Informar
          help: Si está activado, se alertará al usuario sobre infracciones cometidas
      list:
        display: [=username, name, PBXUser]
        title: Usuarios Paranoid
        object_actions:
          _edit: ~
          _delete: ~
          alarmas_historicas: ~
      filter:  ~
      form:
        class: sfGuardUserAdminForm
      edit:
        title: Editar Usuario Paranoid
      new:
        title: Nuevo Usuario Paranoid
