# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  javascripts:    [jquery-1.7.1.min.js, jquery.bgiframe.min.js, hoverIntent.js, superfish.js, supersubs.js, notificaciones.js, ../tooltip/jquery.tooltip.min.js, ../tooltip/lib/jquery.bgiframe.js, ../tooltip/lib/jquery.dimensions.js, highcharts.js, exporting.js, jquery.dataTables.min.js]
  stylesheets:    [main.css, superfish.css, superfish-navbar.css, ../tooltip/jquery.tooltip.css, jquery.dataTables.css]

