generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ReglaDestino
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          regla_destino
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        prefijos_list:
          label: Prefijos
          help: Prefijos donde el usuario tiene permitido llamar
      list:
        title: Destinos
        display: [nombre, importante]
      filter:  ~
      form:
        display: [nombre, importante, prefijos_list]
      edit:
        title: Editar regla
      new:
        title: Nueva regla
