regla_destino:
  class: sfDoctrineRouteCollection
  options:
    model:                ReglaDestino
    module:               regla_destino
    prefix_path:          /regla_destino
    column:               id
    with_wildcard_routes: true

notificaciones:
  class: sfDoctrineRouteCollection
  options:
    model:                Notificaciones
    module:               notificaciones_nuevo
    prefix_path:          /notificaciones_nuevo
    column:               id
    with_wildcard_routes: true

sf_guard_user_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

prefijo:
  class: sfDoctrineRouteCollection
  options:
    model:                Prefijo
    module:               prefijo
    prefix_path:          /prefijo
    column:               id
    with_wildcard_routes: true

regla_costo_por_minuto:
  class: sfDoctrineRouteCollection
  options:
    model:                ReglaCostoPorMinuto
    module:               regla_costo_minuto
    prefix_path:          /regla_costo_minuto
    column:               id
    with_wildcard_routes: true

regla_llamadas_simultaneas:
  class: sfDoctrineRouteCollection
  options:
    model:                ReglaLlamadasSimultaneas
    module:               regla_llamadas_simultaneas
    prefix_path:          /regla_llamadas_simultaneas
    column:               id
    with_wildcard_routes: true

regla_dias:
  class: sfDoctrineRouteCollection
  options:
    model:                ReglaDias
    module:               regla_horario
    prefix_path:          /regla_horario
    column:               id
    with_wildcard_routes: true

historico_alarma:
  class: sfDoctrineRouteCollection
  options:
    model:                HistoricoAlarma
    module:               historico_alarma
    prefix_path:          /historico_alarma
    column:               id
    with_wildcard_routes: true

perfil:
  class: sfDoctrineRouteCollection
  options:
    model:                Perfil
    module:               perfil
    prefix_path:          /perfil
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sf_guard_user
    prefix_path:          /sf_guard_user
    column:               id
    with_wildcard_routes: true

pbx_user:
  class: sfDoctrineRouteCollection
  options:
    model:                PBXUser
    module:               pbx_user
    prefix_path:          /pbx_user
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

#reglas de sfGuard
signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
