# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        P A R A N O I D
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, superfish.css, superfish-navbar.css]

  javascripts:    [jquery-1.7.1.min.js, jquery.bgiframe.min.js, hoverIntent.js, superfish.js, supersubs.js]

  has_layout:     true
  layout:         layout
