<?php

/**
 * EstadisticasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadisticasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadisticasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estadisticas');
    }
}