<?php

/**
 * HistoricoAlarmaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HistoricoAlarmaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HistoricoAlarmaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HistoricoAlarma');
    }
}