<?php

/**
 * ReglaDestinoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReglaDestinoTable extends ReglaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReglaDestinoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReglaDestino');
    }
}