<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/09 01:14:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=paranoid-web',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
