generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ReglaCostoPorMinuto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          regla_costo_por_minuto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        costoMaximo:
          label: Costo
          help: Costo m치ximo por minuto
        importante:
          label: M치xima seguridad
          help: Si la regla es de m치xima seguridad manda un SMS como alerta
      list:
        display: [nombre, importante, costoMaximo]
        title: Costo por minuto
      filter:
        fields:
          importante:
            label: M치xima seguridad
            help:
        display: [nombre, importante, costoMaximo]
      form:    ~
      edit:
        display: [nombre, importante, costoMaximo]
        title: Editar regla
      new:
        display: [nombre, importante, costoMaximo]
        title: Nueva regla
