generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ReglaDias
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          regla_dias
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        desde:
          date_format: hh:mm
        importante:
          label: M치xima seguridad
          help: Si la regla es de m치xima seguridad manda un SMS como alerta
      list:
        display: [nombre, importante, lunes, martes, miercoles, jueves, viernes, sabado, domingo, desde, hasta]
        title: Reglas horarias
        fields:
          desde:
            date_format: hh:mm
          importante:
            label: M치x Seg
          lunes:
            label: L
          martes:
            label: M
          miercoles:
            label: M
          jueves:
            label: J
          viernes:
            label: V
          sabado:
            label: S
          domingo:
            label: D


      filter:
        display: [nombre, importante, lunes, martes, miercoles, jueves, viernes, sabado, domingo, desde, hasta]
        fields:
          importante:
            label: M치xima seguridad
            help:
          desde:
            date_format: hh:mm
      form:    ~
      edit:
        title: Editar regla
        display: [nombre, importante, lunes, martes, miercoles, jueves, viernes, sabado, domingo, desde, hasta]
      new:
        title: Nueva regla
        display: [nombre, importante, lunes, martes, miercoles, jueves, viernes, sabado, domingo, desde, hasta]
