default:
  javascripts:    [jquery-1.7.1.min.js, jquery.bgiframe.min.js, hoverIntent.js, superfish.js, supersubs.js, notificaciones.js]
  stylesheets:    [main.css, superfish.css, superfish-navbar.css]

signinSuccess:
  has_layout: false