generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Perfil
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          perfil
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        reglas_list:
          label: Reglas
          help: Reglas asociadas a este perfil
      list:
        title: Perfiles
        display: [=nombre]
      filter:  ~
      form:    ~
      edit:
        title: Editar perfil
      new:
        title: Nuevo perfil
