<?php

/**
 * NotificacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notificaciones');
    }
}