<?php

/**
 * PBXUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PBXUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PBXUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PBXUser');
    }
}