<?php

/**
 * PrefijoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrefijoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrefijoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Prefijo');
    }
}