<?php

/**
 * ReglaDiasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReglaDiasTable extends ReglaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReglaDiasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReglaDias');
    }
}