<?php

/**
 * ReglaPerfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReglaPerfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReglaPerfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReglaPerfil');
    }
}