<?php

/**
 * ReglaPrefijoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReglaPrefijoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReglaPrefijoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReglaPrefijo');
    }
}