<?php

/**
 * ReglaCostoPorMinutoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReglaCostoPorMinutoTable extends ReglaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReglaCostoPorMinutoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReglaCostoPorMinuto');
    }
}