sfGuardUser:
  columns:
    pbxuser_id: integer(4)
    perfil_id: integer(4)
  relations:
    PBXUser:
      class: PBXUser
      local: pbxuser_id
      foreign: id
      type: one
    Perfil:
      class: Perfil
      local: perfil_id
      foreign: id
      type: one
    HistoricoAlarma:
      type: many
      class: HistoricoAlarma
      local: id
      foreign: user_id

PBXUser:
  tableName: usuario_pbx
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    extension: string
    tecnologia: string
    ultimo_registro: date
    estado: integer

Perfil:
  tableName: perfil
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nombre: string
    descripcion: string
    prefijosProhibidos: string
    prefijosPermitidos: string
    llamadasLocales: boolean
    llamadasInternacionales: boolean
  relations:
    Reglas:
      class: Regla
      type: many
      refClass: ReglaPerfil
      local: perfil_id
      foreign: regla_id
      foreignAlias: Perfiles


ReglaPerfil:
  tableName: regla_perfil
  columns:
    regla_id:
      type: integer(4)
      primary: true
    perfil_id:
      type: integer(4)
      primary: true


HistoricoAlarma:
  tableName: historico_alarmas
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nombre: string
    fecha: date
    detalle: string
    origen: string
    user_id: integer
  relations:
    sfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id


Regla:
  columns:รง
    id:
      type: integer(4)
      primary: true
      autoincrement: true

ReglaDias:
  inheritance:
    extends: Regla
    type: simple
  columns:
    lunes: boolean
    martes: boolean
    miercoles: boolean
    jueves: boolean
    viernes: boolean
    sabado: boolean
    domingo: boolean
    desde: time
    hasta: time

ReglaLlamadasSimultaneas:
  inheritance:
    extends: Regla
    type: simple
  columns:
    cantidadLlamadas: integer

ReglaCostoPorMinuto:
  inheritance:
    extends: Regla
    type: simple
  columns:
    costoMaximo: float

Prefijo:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    descripcion: string
    numero: integer
    