sfGuardUser:
  columns:
    pbxuser_id: integer(4)
    perfil_id: integer(4)
    informarAlertas: boolean
    telefono: string
  relations:
    PBXUser:
      class: PBXUser
      local: pbxuser_id
      foreign: id
      type: one
    Perfil:
      class: Perfil
      local: perfil_id
      foreign: id
      type: one
    HistoricoAlarma:
      type: many
      class: HistoricoAlarma
      local: id
      foreign: user_id

PBXUser:
  tableName: usuario_pbx
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    extension: string
    tecnologia: string
    ultimo_registro: date
    conectado: boolean

Perfil:
  tableName: perfil
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nombre: string
    descripcion: string
  relations:
    Reglas:
      class: Regla
      type: many
      refClass: ReglaPerfil
      local: perfil_id
      foreign: regla_id
      foreignAlias: Perfiles


ReglaPerfil:
  tableName: regla_perfil
  columns:
    regla_id:
      type: integer(4)
      primary: true
    perfil_id:
      type: integer(4)
      primary: true


HistoricoAlarma:
  tableName: historico_alarmas
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nombre: string
    fecha: date
    detalle: string
    origen: string
    user_id: integer
  relations:
    sfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id


Regla:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    nombre: string
    importante: boolean

ReglaDias:
  inheritance:
    extends: Regla
    type: column_aggregation
    keyField: type
    keyValue: regla_dias
  columns:
    lunes: boolean
    martes: boolean
    miercoles: boolean
    jueves: boolean
    viernes: boolean
    sabado: boolean
    domingo: boolean
    desde: time
    hasta: time

ReglaLlamadasSimultaneas:
  inheritance:
    extends: Regla
    type: column_aggregation
    keyField: type
    keyValue: llamadas_simultaneas
  columns:
    cantidadLlamadas: integer

ReglaCostoPorMinuto:
  inheritance:
    extends: Regla
    type: column_aggregation
    keyField: type
    keyValue: costo_por_minuto
  columns:
    costoMaximo: float

Prefijo:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    descripcion: string
    numero: integer
    costoPorMinuto: float

Notificaciones:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    fecha: date
    accion: string
    masInfoURL: string
    regla_id: integer(4)
    user_id: integer
    leida: boolean
  relations:
    Regla:
      class: Regla
      local: regla_id
      foreign: id
      type: one
    Usuario:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one


Estadisticas:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    usuarios: integer
    totales: integer
    ok: integer
    fallidas: integer
    sospechosas: integer
    
EstadisticasLlamadas:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    fecha: string
    llamadas_ok: integer
    llamadas_sospechosas: integer
    llamadas_fallidas: integer